name: Dependency submission
description: Generate and submit dependency graph

inputs:
  jdk-versions:
    description: "Comma-separated list of JDK versions and distributions (supported ones: \"8-zulu\", \"8-temurin\", \"11-temurin\", and \"17-temurin\")"
    required: true

runs:
  using: composite
  steps:
    - name: Set up JDKs
      uses: ./actions/setup-javas
      with:
        jdk-versions: ${{ inputs.jdk-versions }}

    - uses: actions/checkout@v4

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
