name: Dependency submission
description: Generate and submit dependency graph

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Set up JDKs
      uses: ./../setup-javas
      with:
        jdk-versions: "8-temurin"

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
