name: Dependency submission
description: Generate and submit dependency graph

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Set up JDKs
      uses: huanshankeji/.github/actions/setup-javas@7c70a6da5c17910412dab582f4d5f33610fd0c12

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
