name: Gradle check
description: Run Gradle check

inputs:
  jdk-versions:
    description: "Comma-separated list of JDK versions and distributions (supported ones: \"8-zulu\", \"8-temurin\", \"11-temurin\", \"17-temurin\", \"21-temurin\", and \"25-temurin\")"
    required: true
  gh-actor:
    description: "GitHub Packages username (USERNAME for Gradle)"
    required: false
  gh-token:
    description: "GitHub Packages token (TOKEN for Gradle)"
    required: false
  gitlab-private-token:
    description: "GitLab private token (GITLAB_PRIVATE_TOKEN for Gradle)"
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Set up JDKs
      uses: huanshankeji/.github/actions/setup-javas@v0.2.0
      with:
        jdk-versions: ${{ inputs.jdk-versions }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Check with Gradle Wrapper
      shell: bash
      run: ./gradlew check --no-daemon
      env:
        USERNAME: ${{ inputs.gh-actor }}
        TOKEN: ${{ inputs.gh-token }}
        GITLAB_PRIVATE_TOKEN: ${{ inputs.gitlab-private-token }}
