name: Gradle check
description: Run Gradle check

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Set up JDKs
      uses: ./../setup-javas
      with:
        jdk-versions: "8-temurin"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Test with Gradle Wrapper
      shell: bash
      run: ./gradlew test

    - name: Check with Gradle Wrapper
      shell: bash
      run: ./gradlew check
