name: Gradle check
description: Run Gradle check

inputs:
  jdk-versions:
    description: "Comma-separated list of JDK versions and distributions (supported ones: \"8-zulu\", \"8-temurin\", \"11-temurin\", and \"17-temurin\")"
    required: true

runs:
  using: composite
  steps:
    # NOTE: When this composite action is consumed from another repository, relative paths like ./actions/setup-javas
    # resolve against the CONSUMER repo root, not this .github repository. Therefore we must use a fully-qualified
    # action reference for sibling actions.
    - name: Set up JDKs
      uses: huanshankeji/.github/actions/setup-javas@b8b32179d9722d6bb315b9a0c1efff5f1c75e0b1
      with:
        jdk-versions: ${{ inputs.jdk-versions }}

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Test with Gradle Wrapper
      shell: bash
      run: ./gradlew test

    - name: Check with Gradle Wrapper
      shell: bash
      run: ./gradlew check
