name: Gradle check
description: Run Gradle check

inputs:
  jdk-versions:
    description: "Comma-separated list of JDK versions and distributions (supported ones: \"8-zulu\", \"8-temurin\", \"11-temurin\", and \"17-temurin\")"
    required: true

runs:
  using: composite
  steps:
    # IMPORTANT: Call sibling composite action BEFORE checking out the caller repository.
    # If we checkout first, we replace the workspace (which originally contains this .github repo) with the caller repo
    # and then the relative ./actions/... path would no longer exist.
    - name: Set up JDKs
      uses: ./actions/setup-javas
      with:
        jdk-versions: ${{ inputs.jdk-versions }}

    # Now fetch the caller repository so that Gradle can run on its sources.
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Test with Gradle Wrapper
      shell: bash
      run: ./gradlew test

    - name: Check with Gradle Wrapper
      shell: bash
      run: ./gradlew check
