name: Gradle check
description: Run Gradle check

inputs:
  jdk-versions:
    description: "Comma-separated list of JDK versions and distributions (supported ones: \"8-zulu\", \"8-temurin\", \"11-temurin\", and \"17-temurin\")"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Set up JDKs
      uses: ./actions/setup-javas/action.yml
      with:
        jdk-versions: ${{ inputs.jdk-versions }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Test with Gradle Wrapper
      shell: bash
      run: ./gradlew test

    - name: Check with Gradle Wrapper
      shell: bash
      run: ./gradlew check
