name: Gradle Maven publish

on:
  workflow_call:
    inputs:
      jdk-versions:
        description: "Comma-separated JDK versions passed to setup-javas"
        required: true
        type: string
      runs-on:
        description: "Runner label"
        required: true
        type: string

jobs:
  publish:
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
      packages: write
    env:
      ORG_GRADLE_PROJECT_gprUser: ${{ secrets.GPR_USER }}
      ORG_GRADLE_PROJECT_gprKey: ${{ secrets.GPR_KEY }}
      USERNAME: ${{ secrets.GPR_USER }}
      TOKEN: ${{ secrets.GPR_KEY }}
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDKs and Gradle
        uses: huanshankeji/.github/actions/setup-javas-and-gradle@improve-cross-repo-dependency
        with:
          jdk-versions: ${{ inputs.jdk-versions }}
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Publish with Gradle Wrapper
        shell: bash
        run: |
          if [ "${{ github.ref }}" = "refs/heads/release" ]; then
            ./gradlew publishAndReleaseToMavenCentral
          else
            ./gradlew publishAllPublicationsToGitHubPackagesRepository --parallel
          fi
